name: DevExtreme package tests

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [21_2]

jobs:
  build:
    runs-on: devextreme-shr2

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Restore artifacts cache
      uses: actions/cache@v2
      with:
        path: ./artifacts
        key: build-npm-devextreme-artifacts-${{ github.sha }}

    - name: Install packages in devextreme repo
      run: test -d artifacts || npm install --no-audit --no-fund

    - name: Build devextreme repo
      run: test -d artifacts || npm run build-npm-devextreme

    - name: Pack devextreme package
      working-directory: ./artifacts/npm/devextreme
      run: npm pack

    - name: Copy build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: devextreme-npm
        path: ./artifacts/npm/devextreme/devextreme-*.tgz
        retention-days: 1

  test_angular:
    name: Angular wrapper tests
    needs: build
    runs-on: devextreme-shr2
    timeout-minutes: 30

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get sources
      uses: actions/checkout@v2

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Install packages in devextreme repo
      run: npm install --no-audit --no-fund

    - name: Clone devextreme-angular repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: git clone -b ${{github.event.pull_request.head.ref}} https://github.com/${{github.event.pull_request.user.login}}/devextreme-angular ../devextreme-angular-repo

    - name: Clone devextreme-angular repo
      run: |
        test -d ../devextreme-angular-repo || git clone -b 21.2 https://github.com/devexpress/devextreme-angular ../devextreme-angular-repo

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: devextreme-npm
        path: ../devextreme-angular-repo/packages/devextreme-angular

    - name: Install devextreme package
      working-directory: ../devextreme-angular-repo/packages/devextreme-angular
      run: npm install --save-dev $(ls *.tgz)

    - name: Install packages for devextreme-angular
      working-directory: ../devextreme-angular-repo
      run: npm install --no-audit --no-fund

    - name: Update angular metadata
      working-directory: ../devextreme-angular-repo
      run: |
        npm run internal-tool -- update-meta --output-path ./packages/devextreme-angular/metadata/NGMetaData.json --version 21_2 --js-scripts ../DevExtreme/js --exclude js/renovation/
