name: DevExtreme package tests

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [fix-workflow]

jobs:
  build:
    runs-on: devextreme-shr2

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Restore artifacts cache
      uses: actions/cache@v3
      with:
        path: ./artifacts
        key: build-npm-devextreme-artifacts-${{ github.sha }}

    - name: Install packages in devextreme repo
      run: test -d artifacts || npm install --no-audit --no-fund

    - name: Build devextreme repo
      run: test -d artifacts || npm run build-npm-devextreme

    - name: Pack devextreme package
      working-directory: ./artifacts/npm/devextreme
      run: npm pack

    - name: Copy build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: devextreme-npm
        path: ./artifacts/npm/devextreme/devextreme-*.tgz
        retention-days: 1

  test_angular_wrappers:
    name: Angular wrapper tests
    needs: build
    runs-on: devextreme-shr2
    timeout-minutes: 30

    steps:
    - name: Use Node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get sources
      uses: actions/checkout@v3

    - name: Create directory link
      run: cd ../ && ln -s DevExtreme devextreme

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Install packages in devextreme repo
      run: npm install --no-audit --no-fund

    - name: Discover declarations in devextreme repo
      run: npm run discover-declarations

    - name: Clone devextreme-angular repo from PR author fork
      continue-on-error: true
      if: github.event_name == 'pull_request'
      run: |
        REMOTE_URL=https://github.com/${{github.event.pull_request.user.login}}/devextreme-angular
        REMOTE_BRANCH=${{github.event.pull_request.head.ref}}

        if [ "$(git ls-remote --heads $REMOTE_URL $REMOTE_BRANCH | wc -l)" == "1" ]; then
          git clone -b $REMOTE_BRANCH $REMOTE_URL ../devextreme-angular-repo
        fi

    - name: Clone devextreme-angular repo
      run: |
        test -d ../devextreme-angular-repo || git clone -b 22.1 https://github.com/devexpress/devextreme-angular ../devextreme-angular-repo

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: devextreme-npm
        path: ../devextreme-angular-repo/devextreme-setup

    - name: Install devextreme package
      working-directory: ../devextreme-angular-repo
      run: |
        pushd devextreme-setup
        installerName=$(realpath .)/$(ls *.tgz)
        popd
        cd ./packages/devextreme-angular
        npm install --save-dev $installerName
        cd ../sandbox
        npm install --save-dev $installerName
        cd ../../
        npm install --save-dev $installerName

    - name: Install packages for devextreme-angular
      working-directory: ../devextreme-angular-repo
      run: npm install --no-audit --no-fund

    - name: Build with Angular 7
      working-directory: ../devextreme-angular-repo
      run: npm run build

    - name: Run tests with Angular 7
      working-directory: ../devextreme-angular-repo
      run: npx lerna run --scope devextreme-angular gulp -- run.tests
