name: QUnit tests for renovation

on:
  pull_request:
  push:
    branches: [22_2]

jobs:
  build:
    runs-on: devextreme-shr2
    name: Build
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '15'

    - name: Logs
      run: |
        npm --version
        npm config list
