name: Additional QUnit

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [21_2]

jobs:
  build:
    runs-on: devextreme-shr2
    name: Build
    timeout-minutes: 15

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Build
      env:
        DEVEXTREME_TEST_CI: "true"
        DOTNET_CLI_TELEMETRY_OPTOUT: "true"
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
      run: npm run build

    - name: Zip artifacts
      run: |
        7z a -tzip -mx3 -mmt2 artifacts.zip artifacts scss/bundles testing/tests/Renovation/widgets.json

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: devextreme-artifacts
        path: artifacts.zip
        retention-days: 1

  qunit-tests:
    needs: build
    runs-on: devextreme-shr2
    name: ${{ matrix.envs.name }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        envs: [
          { MOBILE_UA: "ios9", CONSTEL: "ui", name: 'ui-iOS9' },
          { MOBILE_UA: "ios9", CONSTEL: "ui.widgets(1/3)", NO_HEADLESS: true, name: 'ui.widgets(1/3)-iOS9' },
          { MOBILE_UA: "ios9", CONSTEL: "ui.widgets(2/3)", NO_HEADLESS: true, name: 'ui.widgets(2/3)-iOS9' }
        ]

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: devextreme-artifacts

    - name: Setup firefox profile
      run: |
        mkdir -p /tmp/firefox-profile
        for p in \
        '"browser.shell.checkDefaultBrowser", false' \
        '"datareporting.policy.dataSubmissionEnabled", false' \
        '"font.name-list.monospace.x-western", "Liberation Mono"' \
        '"font.name-list.sans-serif.x-western", "Liberation Sans"' \
        '"font.name-list.serif.x-western", "Liberation Serif"' ; do echo "user_pref($p);" >> /tmp/firefox-profile/prefs.js; done

#    - name: Update apt
#      run: |
#       sudo apt-get update

#    - name: Setup utils
#      run: |
#        sudo apt-get install -y dbus-x11 httping x11vnc xvfb

    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: devextreme-artifacts

    - name: Unpack artifacts
      run: 7z x artifacts.zip

    - name: Build dotnet
      run: dotnet build build/build-dotnet.sln

    - name: Run QUnit tests
      env:
        CONSTEL: ${{ matrix.envs.CONSTEL }}
        BROWSER: ${{ matrix.envs.BROWSER }}
        JQUERY: ${{ matrix.envs.JQUERY }}
        MOBILE_UA: ${{ matrix.envs.MOBILE_UA }}
        TZ: ${{ matrix.envs.TZ }}
        PERF: ${{ matrix.envs.PERF }}
        NO_HEADLESS: ${{ matrix.envs.NO_HEADLESS }}
        NORENOVATION: "false"
        GITHUBACTION: "true"
        TARGET: "test"
        DISPLAY: ":99"
      run: |
        chmod +x ./docker-ci.sh
        ./docker-ci.sh
